// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Event {
    endpoint:      string;
    keyPairOutput: KeyPairOutput;
    fundOutput:    FundOutput;
}

export interface FundOutput {
    hash: string;
}

export interface KeyPairOutput {
    secretArn: string;
    publicKey: string;
}
